"class stuff"
"writing code for class"
"changing it for the 1st time"
"dinosaur"
"                 _"
"               / _)"
"      _/\/\/\_/ / "
"    _|         / "
"  _|  ( |  (  |  "
" /_.-'|_|--|_| "